// Code generated by SqlToCsharp

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SqlToCsharpSample
{
    public partial class CharacterSlot
    {
        [Key]
        [Column(Order = 0)]
        public int Id { get; set; }
        public int SlotIndex { get; set; }
        public int CharacterId { get; set; }
        public int Weapon1Id { get; set; }
        public int Weapon2Id { get; set; }
        public int Exp { get; set; }
    }
}
